-- ================================================
-- MIXO 3D STORE - FULL SUPABASE DATABASE SCHEMA
-- ================================================

-- 1. Products Table
CREATE TABLE IF NOT EXISTS public.products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  title TEXT,
  category TEXT DEFAULT '3D Print',
  price NUMERIC NOT NULL,
  original_price NUMERIC,
  image TEXT,
  images TEXT[],
  rating NUMERIC DEFAULT 4.8,
  review_count INT DEFAULT 120,
  is_bestseller BOOLEAN DEFAULT false,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Orders Table (Live Dashboard Synced)
CREATE TABLE IF NOT EXISTS public.orders (
  id TEXT PRIMARY KEY,
  customer JSONB NOT NULL,
  items JSONB NOT NULL,
  custom_data JSONB,
  status TEXT DEFAULT 'Processing',
  total NUMERIC,
  date TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. FAQs Table
CREATE TABLE IF NOT EXISTS public.faqs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_ar TEXT NOT NULL,
  question_en TEXT NOT NULL,
  answer_ar TEXT NOT NULL,
  answer_en TEXT NOT NULL,
  category TEXT DEFAULT 'general',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Store Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Realtime Live Tracking for Orders Table
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;

-- Disable RLS for public demo access (or set open policies)
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.faqs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings DISABLE ROW LEVEL SECURITY;

-- 5. Create 3D File Upload Storage Bucket
INSERT INTO storage.buckets (id, name, public) 
VALUES ('3d-files', '3d-files', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public 3D Files Access" ON storage.objects FOR SELECT USING (bucket_id = '3d-files');
CREATE POLICY "Public 3D Files Upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = '3d-files');
